"""Curated, zero-token IELTS Task 2 expression catalog."""

from __future__ import annotations

from typing import Any


TOPIC_LABELS = {
    "education": "教育",
    "technology": "科技",
    "environment": "环境",
    "health": "健康",
    "society_family": "社会与家庭",
    "work_economy": "工作与经济",
    "government_policy": "政府与公共政策",
    "media_culture": "媒体与文化",
    "crime_law": "犯罪与法律",
    "cities_transport": "城市与交通",
}

FUNCTION_LABELS = {
    "core_collocation": "核心搭配",
    "cause_effect": "原因与影响",
    "contrast_concession": "对比与让步",
    "example_argument": "举例与论证",
    "solution": "解决方案",
    "evaluation_stance": "评价与立场",
}

# Each tuple is: expression, Chinese meaning, Chinese usage note, English example, function.
_CATALOG: dict[str, list[tuple[str, str, str, str, str]]] = {
    "education": [
        ("gain practical skills", "获得实用技能", "用于说明教育与就业能力之间的联系。", "Vocational courses help students gain practical skills.", "core_collocation"),
        ("academic performance", "学业表现", "用于讨论成绩、教学质量或学习压力。", "Regular feedback can improve students' academic performance.", "core_collocation"),
        ("equal access to education", "平等接受教育的机会", "用于教育公平和资源分配类题目。", "Governments should ensure equal access to education.", "evaluation_stance"),
        ("place excessive pressure on students", "给学生施加过大压力", "用于分析考试、作业或竞争的负面影响。", "Frequent high-stakes tests may place excessive pressure on students.", "cause_effect"),
        ("broaden students' horizons", "拓宽学生的视野", "用于说明通识教育、旅行或课外活动的价值。", "Studying the arts can broaden students' horizons.", "cause_effect"),
        ("bridge the gap between theory and practice", "弥合理论与实践的差距", "适合论证实习、实验课和职业教育。", "Internships bridge the gap between theory and practice.", "example_argument"),
        ("while academic knowledge is essential", "虽然学术知识很重要", "让步后可转向实践能力或品格教育。", "While academic knowledge is essential, teamwork also matters.", "contrast_concession"),
        ("not only improve grades but also build confidence", "不仅提高成绩，也增强信心", "用于双重正面影响，注意前后结构平行。", "Supportive teachers not only improve grades but also build confidence.", "cause_effect"),
        ("a clear example is project-based learning", "一个明显例子是项目式学习", "用于引出具体教育案例。", "A clear example is project-based learning, which encourages collaboration.", "example_argument"),
        ("provide targeted support", "提供有针对性的支持", "适合讨论弱势学生或个性化教学。", "Schools should provide targeted support for struggling learners.", "solution"),
        ("invest in teacher training", "投资教师培训", "用于提出提升教育质量的政策方案。", "Authorities should invest in teacher training.", "solution"),
        ("adopt a balanced curriculum", "采用均衡的课程体系", "用于调和学术与实践、必修与选修。", "Schools need to adopt a balanced curriculum.", "solution"),
        ("the benefits outweigh the drawbacks", "利大于弊", "用于明确立场，后文必须解释比较依据。", "For most learners, the benefits of online courses outweigh the drawbacks.", "evaluation_stance"),
        ("should remain a central priority", "应继续作为核心优先事项", "用于结论或政府责任类立场。", "Improving basic literacy should remain a central priority.", "evaluation_stance"),
        ("prepare young people for the workplace", "为年轻人进入职场做准备", "用于教育目的与就业衔接。", "Schools should prepare young people for the workplace.", "core_collocation"),
    ],
    "technology": [
        ("rapid technological advances", "快速的技术进步", "用于科技变化的背景句。", "Rapid technological advances have transformed daily life.", "core_collocation"),
        ("digital literacy", "数字素养", "用于教育、就业和信息辨别能力。", "Digital literacy is now an essential workplace skill.", "core_collocation"),
        ("protect personal data", "保护个人数据", "适合隐私、平台责任和网络安全。", "Technology firms must protect personal data.", "solution"),
        ("improve access to information", "改善获取信息的渠道", "用于说明互联网的积极影响。", "Online platforms improve access to information.", "cause_effect"),
        ("reduce face-to-face interaction", "减少面对面交流", "用于分析社交媒体或远程工作的代价。", "Heavy screen use may reduce face-to-face interaction.", "cause_effect"),
        ("widen the digital divide", "扩大数字鸿沟", "用于讨论不同收入或地区的技术不平等。", "Expensive devices can widen the digital divide.", "cause_effect"),
        ("although automation increases efficiency", "虽然自动化提高效率", "让步后可讨论失业或技能转型。", "Although automation increases efficiency, it can displace some workers.", "contrast_concession"),
        ("rather than replace human judgement", "而不是取代人的判断", "用于限制技术角色，常与 should support 搭配。", "AI should support rather than replace human judgement.", "contrast_concession"),
        ("telemedicine illustrates how technology can help", "远程医疗说明了技术如何提供帮助", "用于健康科技的具体论证。", "Telemedicine illustrates how technology can help rural patients.", "example_argument"),
        ("for instance, remote working tools", "例如，远程办公工具", "用于引出效率或灵活性的例子。", "For instance, remote working tools allow flexible schedules.", "example_argument"),
        ("introduce stronger privacy rules", "出台更严格的隐私规定", "用于政府监管方案。", "Governments should introduce stronger privacy rules.", "solution"),
        ("equip workers with new skills", "让劳动者掌握新技能", "用于应对自动化和产业转型。", "Employers should equip workers with new skills.", "solution"),
        ("use technology responsibly", "负责任地使用技术", "适合结论中的个人或机构责任。", "Schools should teach children to use technology responsibly.", "evaluation_stance"),
        ("the advantages depend on how it is regulated", "其优势取决于如何监管", "用于条件式立场，避免绝对化。", "The advantages of AI depend on how it is regulated.", "evaluation_stance"),
        ("streamline routine tasks", "简化常规任务", "用于说明技术提升效率。", "Software can streamline routine tasks in small businesses.", "core_collocation"),
    ],
    "environment": [
        ("reduce carbon emissions", "减少碳排放", "环境题最常用的政策或结果搭配。", "Public transport can reduce carbon emissions.", "core_collocation"),
        ("renewable energy sources", "可再生能源", "用于能源结构和政府投资。", "Countries should invest in renewable energy sources.", "core_collocation"),
        ("protect natural habitats", "保护自然栖息地", "用于生物多样性和城市扩张。", "Stricter planning laws can protect natural habitats.", "solution"),
        ("lead to long-term environmental damage", "导致长期环境破坏", "用于分析短期经济活动的后果。", "Unchecked mining can lead to long-term environmental damage.", "cause_effect"),
        ("put pressure on limited resources", "给有限资源带来压力", "用于人口、消费和城市化影响。", "Rapid population growth puts pressure on limited resources.", "cause_effect"),
        ("raise public awareness of conservation", "提高公众的环保意识", "用于教育和宣传措施。", "School campaigns can raise public awareness of conservation.", "cause_effect"),
        ("despite the short-term cost", "尽管存在短期成本", "让步后强调长期环境收益。", "Despite the short-term cost, clean energy brings lasting benefits.", "contrast_concession"),
        ("economic growth need not come at the expense of nature", "经济增长不必以牺牲自然为代价", "用于反驳经济与环保只能二选一。", "Economic growth need not come at the expense of nature.", "contrast_concession"),
        ("plastic waste is a clear case in point", "塑料垃圾就是一个明显例证", "用于引出具体污染案例。", "Plastic waste is a clear case in point, as it persists for decades.", "example_argument"),
        ("cities such as Copenhagen demonstrate that", "哥本哈根等城市表明", "用于举例说明绿色交通可行性。", "Cities such as Copenhagen demonstrate that cycling can be practical.", "example_argument"),
        ("enforce environmental regulations", "执行环境法规", "强调执行而不只是制定法规。", "Governments must enforce environmental regulations.", "solution"),
        ("offer incentives for cleaner choices", "为更环保的选择提供激励", "适合税收优惠、补贴和绿色消费。", "Authorities can offer incentives for cleaner choices.", "solution"),
        ("a shared responsibility", "共同责任", "用于平衡政府、企业和个人责任。", "Environmental protection is a shared responsibility.", "evaluation_stance"),
        ("a necessary investment in the future", "对未来的必要投资", "用于评价环保支出的长期价值。", "Climate action is a necessary investment in the future.", "evaluation_stance"),
        ("adopt sustainable practices", "采取可持续做法", "适合企业、家庭或城市层面的行动。", "Businesses should adopt sustainable practices.", "core_collocation"),
    ],
    "health": [
        ("maintain a healthy lifestyle", "保持健康的生活方式", "用于个人健康行为的总括表达。", "People need time and support to maintain a healthy lifestyle.", "core_collocation"),
        ("public health services", "公共医疗服务", "用于政府投入和医疗公平。", "Public health services should be affordable and accessible.", "core_collocation"),
        ("preventable diseases", "可预防疾病", "用于饮食、运动、吸烟等话题。", "Regular exercise lowers the risk of preventable diseases.", "core_collocation"),
        ("increase the risk of obesity", "增加肥胖风险", "用于解释不健康饮食或久坐的影响。", "A sedentary lifestyle can increase the risk of obesity.", "cause_effect"),
        ("place a burden on the healthcare system", "给医疗系统带来负担", "用于说明群体健康问题的公共成本。", "Smoking-related illness places a burden on the healthcare system.", "cause_effect"),
        ("improve mental well-being", "改善心理健康", "用于运动、社区和工作生活平衡。", "Green spaces can improve mental well-being.", "cause_effect"),
        ("while individual choice matters", "虽然个人选择很重要", "让步后转向政府或环境责任。", "While individual choice matters, healthy options must be affordable.", "contrast_concession"),
        ("treatment alone is not enough", "仅靠治疗并不足够", "用于强调预防优先。", "Treatment alone is not enough; prevention is equally important.", "contrast_concession"),
        ("school meals provide a practical example", "学校餐食提供了实际例子", "用于说明公共政策如何改变饮食。", "School meals provide a practical example of early prevention.", "example_argument"),
        ("for example, routine health checks", "例如，常规健康检查", "用于引出早发现的措施。", "For example, routine health checks can detect problems early.", "example_argument"),
        ("promote healthier food choices", "促进更健康的饮食选择", "适合标签、教育或补贴措施。", "Clear labels can promote healthier food choices.", "solution"),
        ("expand access to mental health support", "扩大心理健康支持的可及性", "用于学校、职场与公共医疗。", "Governments should expand access to mental health support.", "solution"),
        ("prevention is more effective than cure", "预防胜于治疗", "适合立场或结论，但要结合具体措施。", "In many cases, prevention is more effective than cure.", "evaluation_stance"),
        ("health should not depend on income", "健康不应取决于收入", "用于医疗公平的价值判断。", "Basic health care should not depend on income.", "evaluation_stance"),
        ("encourage regular physical activity", "鼓励规律运动", "用于学校、社区或企业措施。", "Cities can encourage regular physical activity through safe parks.", "solution"),
    ],
    "society_family": [
        ("a strong sense of community", "强烈的社区归属感", "用于邻里、志愿活动和社会联系。", "Local events can create a strong sense of community.", "core_collocation"),
        ("work-life balance", "工作与生活的平衡", "用于家庭时间、远程工作和压力。", "Flexible hours can improve work-life balance.", "core_collocation"),
        ("an ageing population", "人口老龄化", "用于养老、劳动力和家庭责任。", "An ageing population creates new social challenges.", "core_collocation"),
        ("weaken family bonds", "削弱家庭纽带", "用于长工时、迁移或屏幕使用的影响。", "Long working hours may weaken family bonds.", "cause_effect"),
        ("reduce social isolation", "减少社会孤立", "用于社区项目、老人关怀和公共空间。", "Community centres can reduce social isolation.", "cause_effect"),
        ("create conflict between generations", "造成代际冲突", "用于价值观、住房和照护分歧。", "Different expectations can create conflict between generations.", "cause_effect"),
        ("although traditional roles are changing", "虽然传统角色正在改变", "用于让步并讨论更平等的家庭分工。", "Although traditional roles are changing, unpaid care remains uneven.", "contrast_concession"),
        ("independence should not mean disconnection", "独立不应意味着疏离", "用于平衡个人自由与家庭联系。", "Independence should not mean disconnection from family.", "contrast_concession"),
        ("shared childcare is one practical example", "共同育儿是一个实际例子", "用于说明平等分工。", "Shared childcare is one practical example of balanced family roles.", "example_argument"),
        ("volunteer groups show how communities can respond", "志愿团体展示了社区如何应对问题", "用于社区互助论证。", "Volunteer groups show how communities can respond to isolation.", "example_argument"),
        ("provide affordable childcare", "提供可负担的儿童照护", "用于帮助家庭和促进就业。", "Governments should provide affordable childcare.", "solution"),
        ("design age-friendly public spaces", "设计适合老年人的公共空间", "用于应对老龄化。", "Cities should design age-friendly public spaces.", "solution"),
        ("both families and communities have a role to play", "家庭和社区都应发挥作用", "用于责任分配型结论。", "Both families and communities have a role to play.", "evaluation_stance"),
        ("social cohesion is worth protecting", "社会凝聚力值得维护", "用于评价社区政策的长期价值。", "Social cohesion is worth protecting in rapidly changing cities.", "evaluation_stance"),
        ("share caring responsibilities", "共同承担照护责任", "适合家庭分工和性别平等。", "Parents should share caring responsibilities more equally.", "solution"),
    ],
    "work_economy": [
        ("job security", "工作稳定性", "用于就业、自动化和合同制度。", "Many workers value job security more than a high salary.", "core_collocation"),
        ("economic growth", "经济增长", "用于政府政策、投资和生活水平。", "Small businesses make an important contribution to economic growth.", "core_collocation"),
        ("a skilled workforce", "高技能劳动力", "用于教育、培训和竞争力。", "A skilled workforce attracts long-term investment.", "core_collocation"),
        ("create employment opportunities", "创造就业机会", "用于投资、产业和创业的积极影响。", "Green industries can create employment opportunities.", "cause_effect"),
        ("lead to income inequality", "导致收入不平等", "用于分析市场、工资或税制的后果。", "Unequal access to education can lead to income inequality.", "cause_effect"),
        ("boost productivity", "提高生产率", "用于技术、培训和工作环境。", "Flexible working can boost productivity.", "cause_effect"),
        ("although higher pay is attractive", "虽然更高工资很有吸引力", "让步后讨论满意度、稳定或意义。", "Although higher pay is attractive, working conditions also matter.", "contrast_concession"),
        ("growth should be inclusive rather than concentrated", "增长应具有包容性而非集中于少数人", "用于分配公平的立场。", "Economic growth should be inclusive rather than concentrated.", "contrast_concession"),
        ("apprenticeships offer a useful example", "学徒制提供了一个有用例子", "用于技能培训和青年就业。", "Apprenticeships offer a useful example of work-based learning.", "example_argument"),
        ("for instance, support for small firms", "例如，对小企业的支持", "用于政策举例。", "For instance, support for small firms can protect local jobs.", "example_argument"),
        ("provide retraining programmes", "提供再培训项目", "用于应对失业和技术变化。", "Governments should provide retraining programmes for displaced workers.", "solution"),
        ("ensure fair working conditions", "确保公平的工作条件", "用于劳动法、平台经济和企业责任。", "Employers must ensure fair working conditions.", "solution"),
        ("a stable economy benefits society as a whole", "稳定的经济惠及整个社会", "用于总体评价，需配具体机制。", "A stable economy benefits society as a whole.", "evaluation_stance"),
        ("profit should not come before worker welfare", "利润不应凌驾于员工福祉之上", "用于企业责任的明确立场。", "Profit should not come before worker welfare.", "evaluation_stance"),
        ("support long-term career development", "支持长期职业发展", "用于培训、晋升和人才保留。", "Companies should support long-term career development.", "solution"),
    ],
    "government_policy": [
        ("public spending", "公共支出", "用于预算优先级和政府责任。", "Public spending should focus on essential services.", "core_collocation"),
        ("evidence-based policy", "基于证据的政策", "用于评价政策制定质量。", "Evidence-based policy is more likely to produce lasting results.", "core_collocation"),
        ("the public interest", "公共利益", "用于平衡个人自由与集体需要。", "Regulation should serve the public interest.", "evaluation_stance"),
        ("improve social mobility", "促进社会流动", "用于教育、福利和税收政策影响。", "Affordable education can improve social mobility.", "cause_effect"),
        ("create unintended consequences", "产生意想不到的后果", "用于提醒政策可能有副作用。", "Poorly designed subsidies can create unintended consequences.", "cause_effect"),
        ("restore public trust", "恢复公众信任", "用于透明度、腐败和问责。", "Greater transparency can restore public trust.", "cause_effect"),
        ("while regulation is necessary", "虽然监管是必要的", "让步后讨论成本或灵活性。", "While regulation is necessary, it should remain proportionate.", "contrast_concession"),
        ("individual freedom must be balanced against public safety", "个人自由必须与公共安全相平衡", "用于禁令、监控和公共健康。", "Individual freedom must be balanced against public safety.", "contrast_concession"),
        ("public transport subsidies are a case in point", "公共交通补贴就是一个例证", "用于说明政府干预的实际效果。", "Public transport subsidies are a case in point.", "example_argument"),
        ("pilot programmes can test whether a policy works", "试点项目可检验政策是否有效", "用于政策实施方法。", "Pilot programmes can test whether a policy works before expansion.", "example_argument"),
        ("set clear and measurable targets", "设定清晰且可衡量的目标", "用于提升政策执行力。", "Authorities should set clear and measurable targets.", "solution"),
        ("consult affected communities", "征询受影响群体的意见", "用于提高政策公平性和可接受度。", "Officials should consult affected communities.", "solution"),
        ("government intervention is justified when", "在……情况下政府干预是合理的", "用于条件式立场，后接市场失灵或公共风险。", "Government intervention is justified when public safety is at risk.", "evaluation_stance"),
        ("a cost-effective use of public money", "对公共资金具有成本效益的使用", "用于比较不同政策方案。", "Preventive care is a cost-effective use of public money.", "evaluation_stance"),
        ("hold public bodies accountable", "追究公共机构的责任", "用于透明度与治理。", "Independent reviews can hold public bodies accountable.", "solution"),
    ],
    "media_culture": [
        ("cultural heritage", "文化遗产", "用于传统、旅游和身份认同。", "Museums help preserve cultural heritage.", "core_collocation"),
        ("media coverage", "媒体报道", "用于新闻影响、偏见和公众认知。", "Media coverage shapes how people understand social issues.", "core_collocation"),
        ("freedom of expression", "表达自由", "用于审查、艺术和网络内容。", "Freedom of expression is central to an open society.", "evaluation_stance"),
        ("shape public opinion", "影响公众舆论", "用于媒体、广告和名人影响。", "Repeated headlines can shape public opinion.", "cause_effect"),
        ("spread misleading information", "传播误导性信息", "用于社交媒体和新闻可靠性。", "Unverified posts can spread misleading information.", "cause_effect"),
        ("strengthen cultural identity", "增强文化认同", "用于节庆、语言和传统教育。", "Local festivals can strengthen cultural identity.", "cause_effect"),
        ("although global media connects audiences", "虽然全球媒体连接了受众", "让步后讨论本土文化被削弱。", "Although global media connects audiences, local voices may be overlooked.", "contrast_concession"),
        ("popularity does not necessarily indicate quality", "受欢迎并不必然意味着高质量", "用于评价娱乐、网红或节目。", "Popularity does not necessarily indicate quality.", "contrast_concession"),
        ("public broadcasting offers a clear example", "公共广播提供了一个明显例子", "用于文化与教育内容的论证。", "Public broadcasting offers a clear example of educational media.", "example_argument"),
        ("for example, local film festivals", "例如，本地电影节", "用于文化多样性的例子。", "For example, local film festivals give new directors a platform.", "example_argument"),
        ("teach media literacy", "教授媒体素养", "用于应对假消息和算法影响。", "Schools should teach media literacy.", "solution"),
        ("support local artists and creators", "支持本地艺术家和创作者", "用于文化政策和资金分配。", "Public grants can support local artists and creators.", "solution"),
        ("cultural diversity should be preserved", "文化多样性应得到保护", "适合明确文化保护立场。", "Cultural diversity should be preserved in a globalised world.", "evaluation_stance"),
        ("responsible journalism remains essential", "负责任的新闻业仍然至关重要", "用于新闻真实性结论。", "Responsible journalism remains essential to public debate.", "evaluation_stance"),
        ("give underrepresented groups a voice", "让代表性不足的群体发声", "用于媒体包容性和文化表达。", "Digital platforms can give underrepresented groups a voice.", "core_collocation"),
    ],
    "crime_law": [
        ("deter criminal behaviour", "震慑犯罪行为", "用于刑罚有效性和执法。", "Visible policing may deter criminal behaviour.", "core_collocation"),
        ("rehabilitate offenders", "改造罪犯", "用于监禁目的和再犯问题。", "Education can help rehabilitate offenders.", "core_collocation"),
        ("the rule of law", "法治", "用于公平司法和社会秩序。", "The rule of law protects both individuals and society.", "evaluation_stance"),
        ("reduce the rate of reoffending", "降低再犯率", "用于职业培训和社区矫正效果。", "Job training can reduce the rate of reoffending.", "cause_effect"),
        ("address the root causes of crime", "解决犯罪的根本原因", "用于贫困、教育和家庭环境。", "Prevention must address the root causes of crime.", "solution"),
        ("undermine public confidence", "削弱公众信心", "用于执法不公或腐败后果。", "Unequal sentencing can undermine public confidence.", "cause_effect"),
        ("while punishment has a role", "虽然惩罚有其作用", "让步后转向预防和改造。", "While punishment has a role, rehabilitation is also necessary.", "contrast_concession"),
        ("tougher sentences alone are unlikely to solve the problem", "仅靠更严厉的刑罚不太可能解决问题", "用于反驳单一刑罚方案。", "Tougher sentences alone are unlikely to solve the problem.", "contrast_concession"),
        ("youth mentoring provides one example", "青少年辅导提供了一个例子", "用于早期预防犯罪。", "Youth mentoring provides one example of effective prevention.", "example_argument"),
        ("community service can combine punishment with repair", "社区服务可兼顾惩罚与补偿", "用于替代性刑罚论证。", "Community service can combine punishment with repair.", "example_argument"),
        ("invest in early intervention", "投资早期干预", "用于青少年和高风险家庭。", "Governments should invest in early intervention.", "solution"),
        ("provide education and job training in prison", "在监狱中提供教育与职业培训", "用于减少再犯。", "Prisons should provide education and job training.", "solution"),
        ("justice should be both fair and effective", "司法应兼顾公平与有效", "用于平衡性结论。", "Justice should be both fair and effective.", "evaluation_stance"),
        ("public safety must remain the priority", "公共安全必须始终是首要任务", "用于说明政策底线。", "Public safety must remain the priority.", "evaluation_stance"),
        ("ensure equal treatment under the law", "确保法律面前人人平等", "用于司法公正。", "Courts must ensure equal treatment under the law.", "solution"),
    ],
    "cities_transport": [
        ("traffic congestion", "交通拥堵", "城市交通题的基础搭配。", "Traffic congestion wastes time and fuel.", "core_collocation"),
        ("affordable public transport", "可负担的公共交通", "用于交通公平和减排。", "Affordable public transport benefits low-income residents.", "core_collocation"),
        ("pedestrian-friendly neighbourhoods", "适合步行的社区", "用于城市规划与健康。", "Pedestrian-friendly neighbourhoods encourage active travel.", "core_collocation"),
        ("reduce commuting time", "缩短通勤时间", "用于交通投资或远程工作的影响。", "Better rail links can reduce commuting time.", "cause_effect"),
        ("improve urban air quality", "改善城市空气质量", "用于公共交通、限车和绿化。", "Fewer private cars would improve urban air quality.", "cause_effect"),
        ("push up housing costs", "推高住房成本", "用于城市发展和中心区更新的副作用。", "Rapid redevelopment can push up housing costs.", "cause_effect"),
        ("although cars offer convenience", "虽然汽车提供便利", "让步后讨论拥堵、污染或空间占用。", "Although cars offer convenience, they impose wider social costs.", "contrast_concession"),
        ("expansion should not come at the expense of liveability", "扩张不应以牺牲宜居性为代价", "用于城市增长与生活质量的平衡。", "Urban expansion should not come at the expense of liveability.", "contrast_concession"),
        ("bus rapid transit is a practical example", "快速公交是一个实际例子", "用于低成本公共交通方案。", "Bus rapid transit is a practical example of efficient investment.", "example_argument"),
        ("mixed-use development shows how planning can help", "混合用途开发说明规划如何发挥作用", "用于减少通勤和提升便利度。", "Mixed-use development shows how planning can help residents.", "example_argument"),
        ("expand reliable public transport networks", "扩展可靠的公共交通网络", "用于核心交通解决方案。", "Cities should expand reliable public transport networks.", "solution"),
        ("create safe cycling routes", "建设安全的自行车道", "用于绿色交通和健康。", "Local authorities should create safe cycling routes.", "solution"),
        ("prioritise people over private vehicles", "优先考虑人而非私家车", "用于明确城市设计立场。", "City centres should prioritise people over private vehicles.", "evaluation_stance"),
        ("good planning improves quality of life", "良好规划能提升生活质量", "用于总结城市政策的综合效果。", "Good planning improves quality of life for all residents.", "evaluation_stance"),
        ("make essential services easier to reach", "让基本服务更易到达", "用于15分钟城市和公共设施布局。", "Compact neighbourhoods make essential services easier to reach.", "solution"),
    ],
}


def load_expression_catalog() -> list[dict[str, Any]]:
    """Return stable dictionaries for UI rendering and optional personal persistence."""
    rows: list[dict[str, Any]] = []
    for topic, items in _CATALOG.items():
        for index, (expression, meaning, usage_note, example, function) in enumerate(items, start=1):
            rows.append(
                {
                    "catalog_id": f"{topic}:{index:02d}",
                    "origin": "catalog",
                    "topic_category": topic,
                    "function_category": function,
                    "expression": expression,
                    "meaning": meaning,
                    "usage_note": usage_note,
                    "example": example,
                }
            )
    return rows

