[theme]
base = "light"
primaryColor = "#416FA9"
backgroundColor = "#F9FCFF"
secondaryBackgroundColor = "#F3F9FE"
textColor = "#153451"
linkColor = "#10578F"
borderColor = "#D7E1E8"
baseRadius = "16px"
buttonRadius = "12px"
showWidgetBorder = true
